File formater bug fix
aliparlakci/bulk-downloader-for-reddit pull request #227
Opened 2021-03-27 16:34 UTC by aliparlakci

string.strip() does not strictly match the whole word. So, this causes some of the unrelated parts of the filename to be stripped. Replaced it with regex.

Also, string.format() can be used to construct a filename using template instead of doing regex. A good advantage of using curly brackets in schemes :)

2021-03-28 00:22 UTC, Serene-Arc requested changes
Denied

2021-03-28 00:27 UTC, Serene-Arc commented
I also fail to see the reasoning behind using regex in 61b3102, what is the case where there is a problem with it? Also, for future reference, if you do find a case where the code misbehaves, please add a test that would catch that behaviour in the future.

2021-03-29 07:57 UTC, aliparlakci commented
I will revert 8e82252 and add a test for 61b3102

2021-03-29 11:11 UTC, Serene-Arc commented
I added a commit on the main v2 branch for a test that shows the non-existent key error, so maybe rebase off of that too

2021-03-30 08:22 UTC, merged