Add warning for non-unique file name schemes
aliparlakci/bulk-downloader-for-reddit pull request #233
Opened 2021-03-28 00:46 UTC by Serene-Arc

Closes #216 

Adds a logger warning when using a file scheme that cannot be guaranteed to be unique

2021-03-29 07:37 UTC, aliparlakci requested changes
Program behavior should be explained in [README/Folder and File Name Schemes](https://github.com/aliparlakci/bulk-downloader-for-reddit/tree/v2#folder-and-file-name-schemes) also.

2021-03-29 07:37 UTC, aliparlakci commented on bulkredditdownloader/file_name_formatter.py
> +                    f'Post ID not included in this file scheme, so file names are not guaranteed to be unique')
"File names are not guaranteed to be unique as Post IDs are not included in the file scheme. Some files might not be downloaded due to name conflicts."

2021-03-29 23:17 UTC, Serene-Arc commented
The warning has been added to the README

2021-03-30 06:56 UTC, aliparlakci approved these changes

2021-03-30 06:57 UTC, aliparlakci requested changes

2021-03-30 06:57 UTC, aliparlakci commented on bulkredditdownloader/file_name_formatter.py
> +                    f'Post ID not included in this file scheme, so file names are not guaranteed to be unique')
@Serene-Arc

2021-03-30 07:20 UTC, merged